// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VNPay.Models;

namespace VNPay.Migrations
{
    [DbContext(typeof(VNPayContext))]
    partial class VNPayContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VNPay.Models.OrderInfo", b =>
                {
                    b.Property<string>("OrderId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Amount");

                    b.Property<string>("BankCode");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("OrderDescription");

                    b.Property<int>("Status");

                    b.Property<decimal>("vnp_TransactionNo");

                    b.Property<string>("vpn_Message");

                    b.Property<string>("vpn_TxnResponseCode");

                    b.HasKey("OrderId");

                    b.ToTable("OrderInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
